[build]
  publish = "."
  command = "echo 'No build needed - using pre-built admin'"

[build.environment]
  MEDUSA_ADMIN_BACKEND_URL = "https://rebbies-store-y5cp.onrender.com"

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/app/"
  status = 301

[context.production.environment]
  MEDUSA_ADMIN_BACKEND_URL = "https://rebbies-store-y5cp.onrender.com"