[build]
  publish = "."
  command = "echo 'No build needed - using pre-built admin'"

[build.environment]
  MEDUSA_ADMIN_BACKEND_URL = "https://rebbies-store-y5cp.onrender.com"

# Serve assets directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Redirect root to admin
[[redirects]]
  from = "/"
  to = "/app"
  status = 302

# Only redirect non-asset paths to index.html for SPA routing
[[redirects]]
  from = "/app*"
  to = "/index.html"
  status = 200

[context.production.environment]
  MEDUSA_ADMIN_BACKEND_URL = "https://rebbies-store-y5cp.onrender.com"