[build]
  publish = "."
  command = "echo 'No build needed - using pre-built admin'"

[build.environment]
  MEDUSA_ADMIN_BACKEND_URL = "https://rebbies-store-y5cp.onrender.com"

# Serve assets directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# SPA routing - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  MEDUSA_ADMIN_BACKEND_URL = "https://rebbies-store-y5cp.onrender.com"